version: "3.9"

services:
  flask-app:
    build: .
    ports:
      - "80:80"
    environment:
      FLASK_APP: main.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development
      DATABASE_URL: postgresql://flask_user:flask_pass@db:5432/flask_db
      FLASK_DEBUG: "1"
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: flask_user
      POSTGRES_PASSWORD: flask_pass
      POSTGRES_DB: flask_db
    command: postgres -c "listen_addresses=*"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  pgdata:
  pgadmin_data:
