version: "3.9"

services:
  flask-app:
    build: .
    ports:
      - "80:80"
    environment:
      FLASK_APP: main.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: production
    volumes:
      - .:/app
